/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/books/': RouteRecordInfo<'/books/', '/books', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2022-Hunan-Travelling': RouteRecordInfo<'/posts/2022-Hunan-Travelling', '/posts/2022-Hunan-Travelling', Record<never, never>, Record<never, never>>,
    '/posts/2023-Hangzhou-Travelling': RouteRecordInfo<'/posts/2023-Hangzhou-Travelling', '/posts/2023-Hangzhou-Travelling', Record<never, never>, Record<never, never>>,
    '/posts/ArozOS-RPI-Tutorial': RouteRecordInfo<'/posts/ArozOS-RPI-Tutorial', '/posts/ArozOS-RPI-Tutorial', Record<never, never>, Record<never, never>>,
    '/posts/How-To-Build-A-RPI-NAS-Server': RouteRecordInfo<'/posts/How-To-Build-A-RPI-NAS-Server', '/posts/How-To-Build-A-RPI-NAS-Server', Record<never, never>, Record<never, never>>,
    '/posts/Summary-Of-Junior-High-School-Life': RouteRecordInfo<'/posts/Summary-Of-Junior-High-School-Life', '/posts/Summary-Of-Junior-High-School-Life', Record<never, never>, Record<never, never>>,
    '/posts/To-My-16-Year-Old-Self': RouteRecordInfo<'/posts/To-My-16-Year-Old-Self', '/posts/To-My-16-Year-Old-Self', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
  }
}
