/**
 * Generates src/content/content-entries.ts with all content entries
 * including locale pages. This data is used by useContentRoutes
 * instead of relying on lazy-loaded route meta at runtime.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import fg from 'fast-glob'
import matter from 'gray-matter'

interface ContentEntry {
  path: string
  title: string
  slug: string
  lang: string
  date: string
  summary: string
  type: string
  collection: string
}

function extractSlug(filePath: string): string | null {
  // Try frontmatter first
  try {
    const raw = readFileSync(filePath, 'utf8')
    if (raw.startsWith('---')) {
      const { data } = matter(raw)
      if (data.slug)
        return data.slug
    }
  }
  catch {}
  // Fall back to filename
  const name = filePath.split('/').pop() || ''
  return name.replace(/\.(md|vue)$/, '')
}

function extractFrontmatter(filePath: string): Record<string, any> {
  try {
    const raw = readFileSync(filePath, 'utf8')
    if (raw.startsWith('---')) {
      const { data } = matter(raw)
      return data
    }
  }
  catch {}
  return {}
}

async function run() {
  const rootDir = process.cwd()
  const outDir = resolve(rootDir, 'src/content')
  const entries: ContentEntry[] = []

  // Scan all locale content files
  const patterns = [
    'pages/posts/*.md',
    'pages/posts/*.vue',
    'pages/en/posts/*.md',
    'pages/en/posts/*.vue',
    'pages/ja/posts/*.md',
    'pages/ja/posts/*.vue',
    'pages/books/*.md',
    'pages/en/books/*.md',
    'pages/ja/books/*.md',
  ]

  for (const pattern of patterns) {
    const files = await fg.glob(pattern, { cwd: rootDir })
    for (const file of files) {
      const absPath = resolve(rootDir, file)
      const slug = extractSlug(absPath)
      if (!slug)
        continue

      const fm = extractFrontmatter(absPath)

      // Determine locale from path
      const relPath = file.replace(/^pages\//, '')
      const segs = relPath.split('/')
      const pathLocale = (segs.length >= 1 && ['en', 'zh', 'ja'].includes(segs[0])) ? segs[0] : 'zh'
      const collection = (segs.length >= 2 && ['posts', 'books'].includes(segs[1])) ? segs[1] : 'posts'

      entries.push({
        path: `/${relPath.replace(/\.(md|vue)$/, '')}`,
        title: fm.title || slug.replace(/[-_]/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase()),
        slug,
        lang: fm.lang || pathLocale,
        date: fm.date || '',
        summary: fm.summary || '',
        type: fm.type || 'post',
        collection,
      })
    }
  }

  // Generate TypeScript file with the entries array
  const ts = `// Auto-generated by scripts/generate-content-entries.ts
// Do not edit manually. Run \`pnpm build\` to regenerate.

export interface StaticContentEntry {
  path: string
  title: string
  slug: string
  lang: string
  date: string
  summary: string
  type: string
  collection: string
}

export const contentEntries: StaticContentEntry[] = ${JSON.stringify(entries, null, 2)}
`

  writeFileSync(`${outDir}/content-entries.ts`, ts, 'utf8')
  console.log(`✅ Generated ${entries.length} content entries in src/content/content-entries.ts`)
}

void run()
